apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: ohkim-api
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ohkim-api
      tier: frontend
  template:
    metadata:
      labels:
        app: ohkim-api
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: kwx4957/okim-front:9
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets:
      - name: dockersecret
