apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohkim-api
  namespace: ohkim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ohkim-api
      tier: backend
  template:
    metadata:
      labels:
        app: ohkim-api
        tier: backend
    spec:
      containers:
      - image: kwx4957/okim:23
        name: ohkim-api
        ports:
        - containerPort: 8085
          protocol: TCP
      imagePullSecrets:
      - name: dockersecret
