apiVersion: v1
kind: Service
metadata:
  name: ohkim-api
  namespace: ohkim
spec:
  selector:
    app: ohkim-api
    tier: backend
  ports:
    - port: 80
      targetPort: 8085
      protocol: TCP
  type: LoadBalancer
