apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohkim-auth
  namespace: ohkim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ohkim-auth
      tier: auth
  template:
    metadata:
      labels:
        app: ohkim-auth
        tier: auth
    spec:
      containers:
      - image: kwx4957/okim-auth:5
        name: ohkim-auth
        ports:
        - containerPort: 8082
          protocol: TCP
      imagePullSecrets:
      - name: dockersecret
