apiVersion: v1
kind: Service
metadata:
  name: ohkim-auth
  namespace: ohkim
spec:
  selector:
    app: ohkim-auth
    tier: auth
  ports:
    - port: 80
      targetPort: 8082
      protocol: TCP
  type: LoadBalancer
